# Generated by Django 3.2.19 on 2025-03-16 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastaaslan_app', '0003_user_profiles_forum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vidéo', 'verbose_name_plural': 'Vidéos'},
        ),
        migrations.RemoveIndex(
            model_name='forumpost',
            name='rastaaslan__topic_i_f31384_idx',
        ),
        migrations.RemoveIndex(
            model_name='forumtopic',
            name='rastaaslan__categor_dd7b5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='forumtopic',
            name='rastaaslan__is_pinn_d33aca_idx',
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout"),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='URL de la vignette'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(help_text='Identifiant unique de la vidéo sur Twitch', max_length=255, unique=True, verbose_name='ID Twitch'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('VOD', 'VOD'), ('Clip', 'Clip')], max_length=4, verbose_name='Type'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['video_type', 'created_at'], name='rastaaslan__video_t_261157_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['video_id'], name='rastaaslan__video_i_7616bd_idx'),
        ),
    ]
